project_id = "aqnrvcjctfjocrpmknho"

[functions.webflow-import]
verify_jwt = false

[functions.webflow-sync]
verify_jwt = false

[functions.webflow-validate]
verify_jwt = false

[functions.webflow-health-cron]
verify_jwt = false

[functions.navio-import]
verify_jwt = false
